In [2]:
import pandas as pd

fertilizer_df = pd.read_csv("fertilizer_crop_npk_ph.csv")
plant_df = pd.read_csv("Plant_Parameters.csv")

print("========== DATASET 1 ==========")
print(fertilizer_df.shape)
print(fertilizer_df.columns.tolist())
display(fertilizer_df.head())

print("\n========== DATASET 2 ==========")
print(plant_df.shape)
print(plant_df.columns.tolist())
display(plant_df.head())

========== DATASET 1 ==========
(1843, 6)
['Unnamed: 0', 'Crop', 'N', 'P', 'K', 'pH']

   Unnamed: 0              Crop   N   P   K   pH
0           0              Rice  80  40  40  5.5
1           1    Jowar(Sorghum)  80  40  40  5.5
2           2       Barley(JAV)  70  40  45  5.5
3           3             Maize  80  40  20  5.5
4           4  Ragi( naachnnii)  50  40  20  5.5

========== DATASET 2 ==========
(100000, 10)
['pH', 'Soil EC', 'Phosphorus', 'Potassium', 'Urea', 'T.S.P', 'M.O.P', 'Moisture', 'Temperature', 'Plant Type']

,pH,Soil EC,Phosphorus,Potassium,Urea,T.S.P,M.O.P,Moisture,Temperature,Plant Type
0,6.021428,0.237700,15.987947,133.206193,45.627373,16.952809,23.362074,79.234006,52.094083,Carrots
1,6.342420,0.211844,15.305906,137.856536,59.460887,18.378723,22.143606,75.612889,51.349760,Carrots
2,6.684784,0.290343,14.778959,132.994257,53.567383,17.207365,27.448977,77.277833,61.162072,Carrots
3,6.552203,0.407055,12.328408,109.766048,41.053263,12.086209,21.630035,76.426754,72.280843,Carrots
4,6.705262,0.533824,11.215420,102.429536,37.250965,14.953550,24.008938,76.718368,58.710557,Carrots

In [3]:
print("Dataset 1:")
print(fertilizer_df.info())

print("\nDataset 2:")
print(plant_df.info())

Dataset 1:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1843 entries, 0 to 1842
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1843 non-null   int64
 1   Crop        1843 non-null   object
 2   N           1843 non-null   int64
 3   P           1843 non-null   int64
 4   K           1843 non-null   int64
 5   pH          1843 non-null   float64
dtypes: float64(1), int64(4), object(1)
memory usage: 86.5+ KB
None

Dataset 2:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   pH           100000 non-null  float64
 1   Soil EC      100000 non-null  float64
 2   Phosphorus   100000 non-null  float64
 3   Potassium    100000 non-null  float64
 4   Urea         100000 non-null  float64
 5   T.S.P        100000 non-null  float64
 6   M.O.P        100000 non-null  float64
 7   Moisture     100000 non-null  float64
 8   Temperature  100000 non-null  float64
 9   Plant Type   100000 non-null  object
dtypes: float64(9), object(1)
memory usage: 7.6+ MB
None

In [4]:
print("Dataset 1 missing values:")
print(fertilizer_df.isnull().sum())

print("\nDataset 2 missing values:")
print(plant_df.isnull().sum())

Dataset 1 missing values:
Unnamed: 0    0
Crop          0
N             0
P             0
K             0
pH            0
dtype: int64

Dataset 2 missing values:
pH             0
Soil EC        0
Phosphorus     0
Potassium      0
Urea           0
T.S.P          0
M.O.P          0
Moisture       0
Temperature    0
Plant Type     0
dtype: int64

## Clean Dataset 1

In [5]:
# ============================================
# DATASET 1 CLEANING
# ============================================

fertilizer_df = fertilizer_df.copy()

# Remove automatically generated index column
if "Unnamed: 0" in fertilizer_df.columns:
    fertilizer_df.drop(columns=["Unnamed: 0"], inplace=True)

print("Dataset 1 shape:", fertilizer_df.shape)
print("Columns:")
print(fertilizer_df.columns.tolist())

display(fertilizer_df.head())

Dataset 1 shape: (1843, 5)
Columns:
['Crop', 'N', 'P', 'K', 'pH']

               Crop   N   P   K   pH
0              Rice  80  40  40  5.5
1    Jowar(Sorghum)  80  40  40  5.5
2       Barley(JAV)  70  40  45  5.5
3             Maize  80  40  20  5.5
4  Ragi( naachnnii)  50  40  20  5.5